# Generated by Django 5.1.4 on 2024-12-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
