# Generated by Django 5.1.4 on 2024-12-27 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_product_created_at_product_owner_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
